DROP SCHEMA IF EXISTS ESCOLA;
CREATE SCHEMA ESCOLA;
USE ESCOLA;

CREATE TABLE SALA(
	ID_SALA BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CAPACIDADE INT(3) NOT NULL,
    ANDAR INT(2) NOT NULL
)
ENGINE=InnoDB;

CREATE TABLE ALUNO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    EMAIL VARCHAR(255),
    TELEFONE VARCHAR(255),
    ALTURA DECIMAL (3,2)
)
ENGINE=InnoDB;

INSERT INTO SALA(CAPACIDADE, ANDAR) VALUES (40,1);
INSERT INTO SALA(CAPACIDADE, ANDAR) VALUES (35,1);
INSERT INTO SALA(CAPACIDADE, ANDAR) VALUES (38,2);
INSERT INTO ALUNO(NOME,EMAIL,TELEFONE,ALTURA) VALUES ('Jonas Maia', 'maia@nossodominio.com.br', 1123873791, 1.76);
INSERT INTO ALUNO(NOME,EMAIL,TELEFONE,ALTURA) VALUES ('Rafael Cosentino', 'cosentino@nossodominio.com.br', 1123873791, 1.87);

-- ALTERANDO DADOS INCLUSOS ATRAVÉS DO ID
UPDATE ALUNO SET NOME = 'Jhonas Maia' WHERE ID = 1;
UPDATE SALA SET CAPACIDADE = 41 WHERE ID_SALA = 1;

-- VISUALIZAÇÃO DAS TABELAS APÓS ALTERAÇÃO
SELECT*FROM ALUNO;
SELECT*FROM SALA;

-- REMOÇÃO DE DADOS ATRAVÉS DO ID DA TABELA
DELETE FROM SALA WHERE ID_SALA=3;
SELECT*FROM SALA;


