-- INNER JOIN
-- RETORNA OS REGISTROS QUE SÃO COMUNS ÀS DUAS TABELAS
SELECT
	NF.NRO_NOTA, NF.NM_CLIENTE, 
    COUNT(INF.COD_PRODUTO) AS QTD,
    SUM(INF.VL_TOTAL) AS TOTAL
FROM
	NOTA_FISCAL AS NF
INNER JOIN ITEM_NOTA_FISCAL AS INF
	ON NF.NRO_NOTA = INF.NRO_NOTA
GROUP BY NF.NRO_NOTA
ORDER BY QTD, TOTAL DESC;


-- ASC ORDERNAR ASCENDENTE
-- DES ORDERNAR DESCENDENTE

SELECT
	NF.NRO_NOTA, NF.NM_CLIENTE, P.DESC_PRODUTO
FROM NOTA_FISCAL AS NF
INNER JOIN ITEM_NOTA_FISCAL AS INF
	ON NF.NRO_NOTA = INF.NRO_NOTA
INNER JOIN PRODUTO AS P
	ON INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA ASC;

-- LEFT JOIN
-- RETORNAR OS REGISTROS QUE ESTÃO NA TABELA À ESQUERDA
-- (MESMO QUE NÃO ESTEJAM À DIREITA) E OS REGISTRO DA
-- TABELA À DIREITA QUE SÃO COMUNS A ELA.

SELECT
	NF.NNRO_NOTA, NF.NM_CLIENTE, P.DESC_PRODUTO
FROM NOTA_FISCAL AS NF
LEFT JOIN ITEM_NOTA_FISCAL AS INF
	ON NF.NRO_NOTA = INF.NRO_NOTA
LEFT JOIN PRODUTO AS P
	ON INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA ASC;

-- RIGHT JOIN
-- USAMOS PARA EXIBIR OS REGISTROS QUE ESTÃO NA TABELA
-- À DIREITA (MESMO QUE NÃO ESTEJAM NA TABELA À
-- ESQUERDA) E OS REGISTROS DA TABELA À ESQUERDA
-- QUE SÃO COMUNS À DIREITA
SELECT
	NF.NRO_NOTA, NF.NM_CLIENTE, P.DESC_PRODUTO
FROM NOTA_FISCAL AS NF
RIGHT JOIN ITEM_NOTA_FISCAL AS INF
	ON NF.NRO_NOTA = INF.NRO_NOTA
RIGHT JOIN PRODUTO AS P
	ON INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA ASC;


