DROP SCHEMA IF EXISTS LIVRARIA;
CREATE SCHEMA LIVRARIA;
USE LIVRARIA;

CREATE TABLE EDITORA(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ANO_NASCIMENTO DATETIME NOT NULL,
    NACIONAL BOOLEAN NOT NULL
)
ENGINE=InnoDB;

INSERT INTO EDITORA (NOME, EMAIL, ANO_NASCIMENTO, NACIONAL) VALUE ('Saraiva', 'saraiva@gmail.com', '1992-04-02', 1);
INSERT INTO EDITORA (NOME, EMAIL, ANO_NASCIMENTO, NACIONAL) VALUE ('seuJoaoLivro', 'joaolivraria@gmail.com', '2025-08-03', 1);
INSERT INTO EDITORA (NOME, EMAIL, ANO_NASCIMENTO, NACIONAL) VALUE ('caralho livro', 'caralho@gmail.com', '2012-03-04', 0);


UPDATE EDITORA SET NOME = 'Saraivo' WHERE ID = 1;
UPDATE EDITORA SET EMAIL = 'saraivo@gmail.com' WHERE ID = 1;
UPDATE EDITORA SET NOME = 'Livros Gostoso' WHERE ID = 2;

DELETE FROM EDITORA WHERE ID = 3;
SELECT*FROM EDITORA