CREATE DATABASE PEDICURE;
USE PEDICURE;

CREATE TABLE CLIENTE(
	ID_CLIENTE INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(255),
    DATA_NASCIMENTO DATETIME NOT NULL
);

CREATE TABLE AGENDA(
	ID_AGENDA INT NOT NULL  PRIMARY KEY,
    NOME VARCHAR(255)
);

CREATE TABLE ATENDIMENTO(
	ID INT NOT NULL PRIMARY KEY,
    DT_INICIO DATETIME NOT NULL,
	ID_CLIENTE INT NOT NULL,
    ID_AGENDA INT NOT NULL,
    DT_FIM DATETIME NOT NULL,
	CONSTRAINT FK_ID_CLIENTE_ATENDIMENTO
		FOREIGN KEY (ID_CLIENTE)
		REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT FK_ID_AGENDA_ATENDIMENTO
		FOREIGN KEY (ID_AGENDA)
		REFERENCES AGENDA(ID_AGENDA)
);